general {
    lock_cmd = pidof hyprlock || hyprlock       # command to run when locking
    before_sleep_cmd = loginctl lock-session    # lock screen before system suspends
}

# 10-minute sleep timeout rule
listener {
    timeout = 600                               # 10 minutes in seconds (10 x 60)
    on-timeout = systemctl suspend              # suspend command
}
